param(
    [Parameter(Mandatory = $false)]
    [ValidateSet("prepare", "start", "build", "serve", "clean")]
    [string]$Mode = "start",

    [Parameter(Mandatory = $false)]
    [string]$SiteDir,

    [Parameter(Mandatory = $false)]
    [int]$Port = 3000,

    [Parameter(Mandatory = $false)]
    [switch]$Recreate,

    [Parameter(Mandatory = $false)]
    [switch]$OpenBrowser
)

$ErrorActionPreference = "Stop"

function Assert-CommandExists {
    param([string]$Name)

    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

function Invoke-Step {
    param(
        [string]$WorkingDirectory,
        [string]$Command,
        [string[]]$Arguments
    )

    Push-Location $WorkingDirectory
    try {
        & $Command @Arguments
        if ($LASTEXITCODE -ne 0) {
            throw "$Command $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
        }
    }
    finally {
        Pop-Location
    }
}

function Initialize-Site {
    param(
        [string]$TargetDir,
        [bool]$ForceRecreate
    )

    if ($ForceRecreate -and (Test-Path $TargetDir)) {
        Write-Host "Removing existing site scaffold at: $TargetDir"
        Remove-Item -Path $TargetDir -Recurse -Force
    }

    if (-not (Test-Path $TargetDir)) {
        $parent = Split-Path -Parent $TargetDir
        if (-not (Test-Path $parent)) {
            New-Item -Path $parent -ItemType Directory -Force | Out-Null
        }

        Write-Host "Creating Docusaurus scaffold at: $TargetDir"
        Invoke-Step -WorkingDirectory $parent -Command "npx" -Arguments @("--yes", "create-docusaurus@latest", $TargetDir, "classic", "--javascript", "--package-manager", "npm")
    }
}

function Sync-PlatformDocs {
    param(
        [string]$SourceDir,
        [string]$TargetSiteDir
    )

    $docsTarget = Join-Path $TargetSiteDir "docs"
    if (-not (Test-Path $docsTarget)) {
        New-Item -Path $docsTarget -ItemType Directory -Force | Out-Null
    }

    Get-ChildItem -Path $docsTarget -Force | Remove-Item -Recurse -Force

    $excludedNames = @(".github", "docusaurus")

    Get-ChildItem -Path $SourceDir -Force | Where-Object {
        $excludedNames -notcontains $_.Name
    } | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination $docsTarget -Recurse -Force
    }

    $sidebarsSource = Join-Path $SourceDir "docusaurus\sidebars.js"
    if (-not (Test-Path $sidebarsSource)) {
        throw "Missing sidebars file at $sidebarsSource"
    }

    Copy-Item -Path $sidebarsSource -Destination (Join-Path $TargetSiteDir "sidebars.js") -Force
}

function Write-DocusaurusConfig {
        param([string]$TargetSiteDir)

        $configContent = @'
// Auto-generated by scripts/preview-platform-docs.ps1
// Keep this minimal and deterministic for local preview/build validation.
module.exports = {
    title: 'Platform Docs',
    tagline: 'Security workflow platform documentation',
    url: 'http://localhost',
    baseUrl: '/',
    onBrokenLinks: 'throw',
    onBrokenMarkdownLinks: 'warn',
    favicon: 'img/favicon.ico',
    organizationName: 'local',
    projectName: 'platform-docs',
    i18n: {
        defaultLocale: 'en',
        locales: ['en']
    },
    presets: [
        [
            'classic',
            {
                docs: {
                    routeBasePath: '/docs',
                    sidebarPath: require.resolve('./sidebars.js')
                },
                blog: false,
                theme: {
                    customCss: require.resolve('./src/css/custom.css')
                }
            }
        ]
    ],
    themeConfig: {
        navbar: {
            title: 'Platform Docs',
            items: [
                {
                    type: 'docSidebar',
                    sidebarId: 'docs',
                    position: 'left',
                    label: 'Docs'
                }
            ]
        },
        prism: {
            theme: require('prism-react-renderer').themes.github,
            darkTheme: require('prism-react-renderer').themes.dracula
        }
    }
};
'@

        Set-Content -Path (Join-Path $TargetSiteDir "docusaurus.config.js") -Value $configContent -NoNewline
}

function Write-HomeRedirectPage {
    param([string]$TargetSiteDir)

    $candidates = @(
        "src\pages\index.js",
        "src\pages\index.jsx",
        "src\pages\index.ts",
        "src\pages\index.tsx",
        "src\pages\index.mdx"
    )

    foreach ($relativePath in $candidates) {
        $candidatePath = Join-Path $TargetSiteDir $relativePath
        if (Test-Path $candidatePath) {
            Remove-Item -Path $candidatePath -Force
        }
    }

    $redirectPage = @'
import React, {useEffect} from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';

export default function Home() {
  const target = useBaseUrl('/docs/intro');

  useEffect(() => {
    window.location.replace(target);
  }, [target]);

  return (
    <main style={{padding: '2rem'}}>
      <p>
        Redirecting to <a href={target}>{target}</a>...
      </p>
    </main>
  );
}
'@

    Set-Content -Path (Join-Path $TargetSiteDir "src\pages\index.js") -Value $redirectPage -NoNewline
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$platformDocsDir = Join-Path $repoRoot "platform-docs"

if (-not (Test-Path $platformDocsDir)) {
    throw "platform-docs directory not found at $platformDocsDir"
}

if ([string]::IsNullOrWhiteSpace($SiteDir)) {
    $SiteDir = Join-Path $repoRoot ".tmp\platform-docs-site"
}

Assert-CommandExists -Name "node"
Assert-CommandExists -Name "npm"
Assert-CommandExists -Name "npx"

if ($Mode -eq "clean") {
    if (Test-Path $SiteDir) {
        Write-Host "Removing site directory: $SiteDir"
        Remove-Item -Path $SiteDir -Recurse -Force
    }
    else {
        Write-Host "Nothing to clean. Site directory does not exist: $SiteDir"
    }
    exit 0
}

Initialize-Site -TargetDir $SiteDir -ForceRecreate:$Recreate.IsPresent
Sync-PlatformDocs -SourceDir $platformDocsDir -TargetSiteDir $SiteDir
Write-HomeRedirectPage -TargetSiteDir $SiteDir
Write-DocusaurusConfig -TargetSiteDir $SiteDir

if (Test-Path (Join-Path $SiteDir "package-lock.json")) {
    Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("ci")
}
else {
    Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("install")
}

switch ($Mode) {
    "prepare" {
        Write-Host "Prepared preview site at: $SiteDir"
    }
    "build" {
        Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("run", "build")
        Write-Host "Build complete. Output folder: $(Join-Path $SiteDir 'build')"
    }
    "serve" {
        Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("run", "build")
        if ($OpenBrowser) {
            Start-Process "http://localhost:$Port/"
        }
        Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("run", "serve", "--", "--host", "0.0.0.0", "--port", "$Port")
    }
    "start" {
        if ($OpenBrowser) {
            Start-Process "http://localhost:$Port/"
        }
        Invoke-Step -WorkingDirectory $SiteDir -Command "npm" -Arguments @("run", "start", "--", "--host", "0.0.0.0", "--port", "$Port")
    }
    default {
        throw "Unsupported mode: $Mode"
    }
}
